# AgentsFactory/user_data/config.yaml

version: 1

prompts:
  planner_prompt: planner_prompt_v1

tools:
  # ===== Core / Time =====
  uuid4:
    ref: uuid4
  now:
    ref: now
  today:
    ref: today
  iso_timestamp:
    ref: iso_timestamp

  # ===== Utils =====
  random_choice:
    ref: random_choice
  random_int:
    ref: random_int
  safe_get:
    ref: safe_get

agents:
  planner_agent:
    model: openai:gpt-4o-mini
    tools: []
    prompt: planner_prompt
    description: "Planner..."
    output_format: str

pipeline:
  - planner_agent